/**
 * All empirical/hypothesis constants live here, per the final specs:
 * "Empirical constants parameterized in config, not magic undocumented
 * literals". Defaults are the cycle-3 hypothesis values; G2 tuning owns
 * their final values. Auto-adaptation may move the marked fields by at most
 * ±20% of these defaults.
 */

export type Stance = "regular" | "goofy";
export type AssistLevel = 0 | 1 | 2;
export type AssistPreset = "experienced" | "classic" | "streamlined";
export const ASSIST_LEVEL_BY_PRESET: Readonly<Record<AssistPreset, AssistLevel>> = {
  experienced: 0,
  classic: 1,
  streamlined: 2,
};
export const ASSIST_PRESET_BY_LEVEL: Readonly<Record<AssistLevel, AssistPreset>> = {
  0: "experienced",
  1: "classic",
  2: "streamlined",
};
export type BothClickMeans = "ignore" | "push" | "ollie";
/** Player-facing gesture gain. It affects trick recognition, never propulsion. */
export const FLICK_SENSITIVITY_MIN = 0.6;
export const FLICK_SENSITIVITY_MAX = 1.6;
export const DEFAULT_FLICK_SENSITIVITY = 1;
/**
 * How the player's kick gesture chooses which end of the board pops:
 *
 * - 'motionTap' (shipping): lift one planted role and quickly replant it near
 *   its prior position. Tail retap = ollie, nose retap = nollie. Mouse-button
 *   state is ignored.
 * - 'buttonSide' (legacy Skate-like mapping): with BOTH feet planted the
 *   BUTTON decides — LMB/primary = back-foot kick (ollie family), RMB/secondary
 *   = front-foot kick (nollie family) — instantly, both fingers staying on the
 *   board like a real ollie stance. A short stable-contact debounce rejects a
 *   click generated by the initial finger slap. Push never comes from clicks
 *   in this mode (Ctrl/trackpad travel cover it), which removes the
 *   push-vs-ollie lookahead latency entirely.
 * - 'plantMask' (legacy/advanced mapping): the planted foot decides.
 *   Both-planted click follows `bothClickMeans`. This does not pretend that a
 *   report-level Windows click identifies an individual contact.
 */
export type KickAttribution = "motionTap" | "buttonSide" | "plantMask";

export interface InputProfile {
  stance: Stance;
  /** Degrees; hand approach angle mapping pad axes → board local. */
  padYawOffset: number;
  /**
   * Gain applied to post-pop flick/sweep evidence. Optional for compatibility
   * with profiles and traces recorded before profile v6; normalization always
   * supplies the default value.
   */
  flickSensitivity?: number;
  swapFeet: boolean;
  assistLevel: AssistLevel;
  /** Named player-facing bundle; assistLevel remains the deterministic index. */
  assistPreset?: AssistPreset;
  bothClickMeans: BothClickMeans;
  /** Motion/click→kick-side policy (see KickAttribution). */
  kickAttribution: KickAttribution;
  /** Treat OS tap-to-click primary edges as kicks. */
  tapToClickIsKick: boolean;
  accessibility: {
    reducedMotion: boolean;
    highContrastHud: boolean;
  };
}

export const DEFAULT_INPUT_PROFILE: InputProfile = deepFreezeConfig({
  stance: "regular",
  padYawOffset: 0,
  flickSensitivity: DEFAULT_FLICK_SENSITIVITY,
  swapFeet: false,
  assistLevel: 1,
  assistPreset: "classic",
  bothClickMeans: "ollie",
  kickAttribution: "motionTap",
  tapToClickIsKick: false,
  accessibility: {
    reducedMotion: false,
    highContrastHud: false,
  },
} as InputProfile);

/**
 * Convert persisted or recorded profile data into a complete, safe runtime
 * profile. Profiles cross a storage/trace boundary, so callers must not trust
 * enum values, booleans, or finite calibration angles merely because the data
 * was once produced by this application.
 */
export function normalizeInputProfile(value: unknown): InputProfile {
  const raw = value !== null && typeof value === "object"
    ? value as Partial<InputProfile>
    : {};
  const base = DEFAULT_INPUT_PROFILE;
  const preset: AssistPreset | undefined =
    raw.assistPreset === "experienced" ||
    raw.assistPreset === "classic" ||
    raw.assistPreset === "streamlined"
      ? raw.assistPreset
      : undefined;
  const level: AssistLevel = preset !== undefined
    ? ASSIST_LEVEL_BY_PRESET[preset]
    : raw.assistLevel === 0 || raw.assistLevel === 1 || raw.assistLevel === 2
      ? raw.assistLevel
      : base.assistLevel;
  const padYawOffset = typeof raw.padYawOffset === "number" && Number.isFinite(raw.padYawOffset)
    ? Math.max(-180, Math.min(180, raw.padYawOffset))
    : base.padYawOffset;
  const flickSensitivity =
    typeof raw.flickSensitivity === "number" && Number.isFinite(raw.flickSensitivity)
      ? Math.max(FLICK_SENSITIVITY_MIN, Math.min(FLICK_SENSITIVITY_MAX, raw.flickSensitivity))
      : DEFAULT_FLICK_SENSITIVITY;
  const accessibility: Partial<InputProfile["accessibility"]> =
    raw.accessibility !== null && typeof raw.accessibility === "object"
      ? raw.accessibility
      : {};

  return deepFreezeConfig({
    stance: raw.stance === "goofy" || raw.stance === "regular" ? raw.stance : base.stance,
    padYawOffset,
    flickSensitivity,
    swapFeet: typeof raw.swapFeet === "boolean" ? raw.swapFeet : base.swapFeet,
    assistLevel: level,
    assistPreset: ASSIST_PRESET_BY_LEVEL[level],
    bothClickMeans:
      raw.bothClickMeans === "ignore" || raw.bothClickMeans === "push" || raw.bothClickMeans === "ollie"
        ? raw.bothClickMeans
        : base.bothClickMeans,
    kickAttribution:
      raw.kickAttribution === "motionTap" ||
      raw.kickAttribution === "buttonSide" ||
      raw.kickAttribution === "plantMask"
        ? raw.kickAttribution
        : base.kickAttribution,
    tapToClickIsKick:
      typeof raw.tapToClickIsKick === "boolean" ? raw.tapToClickIsKick : base.tapToClickIsKick,
    accessibility: {
      reducedMotion:
        typeof accessibility.reducedMotion === "boolean"
          ? accessibility.reducedMotion
          : base.accessibility.reducedMotion,
      highContrastHud:
        typeof accessibility.highContrastHud === "boolean"
          ? accessibility.highContrastHud
          : base.accessibility.highContrastHud,
    },
  });
}

export interface RecognitionConfig {
  /** Confidence to open a label (hypothesis 0.55). */
  cEnter: number;
  /** Confidence to keep a label open — hysteresis (hypothesis 0.40). */
  cExit: number;
  /** Same-family replacement margin (hypothesis 0.15). */
  replaceMargin: number;
  /** Click-centered classification window, ms (hypothesis 40–80). */
  popLookbackMs: number;
  popLookaheadMs: number;
  /** Two contacts must already be continuously planted this long before a click can pop. */
  stableClickContactMs: number;
  /** Air trick window after pop for flick/sweep classification, ms. */
  airTrickWindowMs: number;
  /** Minimum free-foot speed (pad units/s) to read a flick. ±20% auto ok. */
  flickSpeedMin: number;
  /** Below this contact speed a planted foot counts as holding. */
  plantSpeedEps: number;
  /** Sweep minimum integrated yaw (radians) to classify a shuv. */
  sweepMinAngleRad: number;
  /** Nose-lift prep velocity threshold distinguishing ollie prep from noise. */
  prepLiftSpeedMin: number;
  // --- M5 shuv naming/target (hypothesis) --------------------------------
  /** Shuv rotation target, degrees (180 first ship; 360 deferred). */
  shuvTargetDeg: number;
  /**
   * Minimum |completed yaw| (degrees) for the OUTCOME namer to call a shuv
   * 'fs-shuv'/'bs-shuv' rather than fall back to the base pop label. Set safely
   * above any incidental yaw a plain ollie accrues.
   */
  shuvNameMinDeg: number;
}

export interface FootTrackerConfig {
  /** Soft recenter hold time while both planted and still, ms (250–400). */
  recenterHoldMs: number;
  /** Dual-lift ballistic prediction window before clearing feet, ms (150–250). */
  ballisticPredictMs: number;
  /** After dual lift, rebind window before IDs are considered fresh, ms (400–600). */
  dualLiftClearMs: number;
  /** Max reassignments/min while held before tracker degrades gracefully. */
  idThrashWarnPerMin: number;
  // --- M3 additions -----------------------------------------------------
  /**
   * EMA smoothing factor (0..1) for foot velocity, segment angular velocity and
   * midpoint velocity finite differences. Higher = snappier / noisier, lower =
   * smoother / laggier. New sample weight per update.
   */
  velEmaAlpha: number;
  /**
   * Spatial rebind radius in CALIBRATED pad units. On re-plant after a lift a
   * contact rebinds to a remembered role only if within this distance of that
   * role's last position; otherwise it is a fresh assignment.
   */
  rebindRadius: number;
  /**
   * Soft-recenter drift rate, 1/s. Once both feet have been planted and nearly
   * still for `recenterHoldMs`, the rest pose eases toward the current pose at
   * this rate (per second), never in a sudden jump. `restNew = rest + (cur -
   * rest) * clamp(recenterRateHz * dt, 0, 1)`.
   */
  recenterRateHz: number;
  /** Minimum lifted duration for a deliberate physical retap, rejecting one-report dropout. */
  motionTapMinLiftMs: number;
  /** Maximum lift-to-replant duration that still reads as a tap. */
  motionTapMaxLiftMs: number;
  /** Maximum calibrated distance from the role's pre-lift position. */
  motionTapReplantRadius: number;
}

export interface PopConfig {
  /** Internal physics substeps used to deliver the physical pop impulse. */
  actuationSubsteps: number;
  /**
   * Vertical pop impulse range, N·s at loaded board+rider scale (M4 —
   * retuned from the cycle-3 placeholders so pop heights land in the playable
   * 0.25–0.8 m band at boardMass 2.4: v0 = jY/m, h ≈ v0²/2g).
   * jY = jMin + q·(jMax − jMin) where q ∈ [0,1] is pop prep quality.
   */
  jMin: number;
  jMax: number;
  /** Consistent binary base-pop strength; post-pop swipes shape the trick. */
  baseQuality: number;
  /** Pitch bias factor applied to the pop pitch torque impulse (spec §3.2). */
  pitchBias: number;
  /**
   * Pitch torque impulse per N·s of vertical pop (M4, hypothesis): the pop's
   * torque impulse about the board-right axis is
   * `pitchBias · pitchTorqueScale · jY` (nose-up for ollie, mirrored for
   * nollie). Tuned so an UNCAUGHT max-q ollie lands DIRTY (~30° cone) while a
   * caught one lands CLEAN — catching matters, per the M4 feel goals.
   */
  pitchTorqueScale: number;
  /** Hard clamp on the pop pitch torque impulse magnitude, N·m·s (SimWorld). */
  pitchTorqueImpulseMax: number;
  /** Assisted ollie/nollie pitch target at the end of the snap phase. */
  noseUpTargetDeg: number;
  /** Steps to hold the visible nose-up/nose-down target after takeoff. */
  snapHoldSteps: number;
  /** Step by which the front-foot guide has levelled the board for landing. */
  levelEndSteps: number;
  /** Pitch PD gains and torque clamp for the force-based levelling phase. */
  levelKp: number;
  levelKd: number;
  levelTorqueMax: number;
  /**
   * Prep-lift pad speed (calibrated units/s) at which the crispness component
   * of pop quality saturates to 1 (M4, hypothesis). Lifts slower than
   * `recognition.prepLiftSpeedMin` contribute zero crispness.
   */
  prepLiftSpeedForMaxQ: number;
  /** Pop quality weights (sum ≤ 1): q = qTimingWeight·timing + qCrispWeight·crisp. */
  qTimingWeight: number;
  qCrispWeight: number;
  /**
   * Steps after the pop impulse within which the board must actually leave
   * the ground; otherwise the pop "fizzles" (board blocked) and the FSM
   * returns to ground with the label cancelled (M4, hypothesis — failure is
   * never silent/undefined per final-input-and-trick-spec §7).
   */
  groundLeaveTimeoutSteps: number;
}

export interface FlipConfig {
  /** Max flip angular speed, rad/s (hypothesis 12–18). */
  omegaFlipMax: number;
  /** PD gains for flip torque tracking. */
  kp: number;
  kd: number;
  /** Torque clamp per assist level, N·m. */
  tauMax: [number, number, number];
  /** One-shot roll impulse budget when a flip intent first opens, N·m·s. */
  impulseMax: [number, number, number];
  /** One-shot yaw impulse budget when a shuv intent first opens, N·m·s. */
  shuvImpulseMax: [number, number, number];
  /** Steps over which the bounded target guide decays to zero after recognition. */
  guideDecaySteps: number;
  // --- M5 flick/sweep classification + envelopes (hypothesis) -----------
  /**
   * Axis-dominance ratio for the shuv-vs-flip conflict (final-input-and-trick
   * §3.1): the free foot's lateral (across-board) speed must exceed its
   * longitudinal (along-board) speed by this factor for a LATERAL-dominant
   * flick → flip; otherwise arc/yaw evidence is allowed to win → shuv.
   */
  axisDominanceRatio: number;
  /**
   * Minimum integrated lateral pad displacement (calibrated units) over the
   * flick path to confirm a flick (rejects a single noisy fast frame). ~one
   * board-half of pad travel.
   */
  flickPathMinLen: number;
  /**
   * Lateral pad speed (calibrated units/s) at which the flick intensity s
   * saturates to 1. s = clamp((peakLatSpeed − flickSpeedMin)/(flickSpeedForMaxS
   * − flickSpeedMin), 0, 1); omegaTarget = s·sign·omegaFlipMax.
   */
  flickSpeedForMaxS: number;
  /** Target yaw rate magnitude for a shuv envelope, rad/s (about board up). */
  shuvOmegaMax: number;
  /**
   * Torque clamp per assist level for the SHUV yaw envelope, N·m. Separate from
   * `tauMax` (which drives flip roll) because the board's yaw inertia about the
   * up axis is ~17× its roll inertia about the long axis — the same clamp would
   * barely spin a shuv. Sized so a shuv reaches its 180° target within airtime.
   */
  shuvTauMax: [number, number, number];
  /**
   * Catch-time quantize cone half-width per assist level, degrees. When the
   * integrated flip roll (or shuv yaw) at catch lands within this cone of the
   * nearest k·360° (flip) / k·180° (shuv), extra axis-damping bleeds the
   * residual spin so the trick settles ON the level (final-physics §3.4). L0 is
   * 0 → L0 NEVER snaps (quantize off). NEVER a pose write.
   */
  quantizeConeDeg: [number, number, number];
  /**
   * Fraction of the on-axis spin removed at catch when inside the quantize cone,
   * per assist level. Applied ON TOP of the base catch damping, only about the
   * trick axis. L0 is 0 by construction. L2 > L1 (stronger snap).
   */
  quantizeExtraDamp: [number, number, number];
  /**
   * Minimum |completed rotations| (turns) for the OUTCOME namer to call a flip
   * 'kickflip'/'heelflip' rather than fall back to the base pop label
   * (final-input-and-trick §7: names from board-state history — a flick whose
   * rotation died early is named for what physically happened). Set safely above
   * any incidental roll a plain/dirty ollie accrues about its long axis.
   */
  nameMinTurns: number;
}

export interface CatchConfig {
  /** Catch volume radius, m board-local (hypothesis 0.12–0.18). ±20% auto ok. */
  volumeRadius: number;
  /** Catch window after pop apex, ms. */
  windowMs: number;
  /** Angular damping applied on catch per assist level. */
  assistScale: [number, number, number];
  /** Base catch gain multiplied by assistScale. */
  catchGain: number;
  /** Hard torque-impulse budget for catch damping by assist preset, N·m·s. */
  angularImpulseMax: [number, number, number];
  /**
   * When true (M4 default, hypothesis) the catch window opens only after the
   * vertical apex (lv.y ≤ 0); a replant during the ascent does not catch.
   * When false any mid-air replant into a catch volume catches.
   */
  apexOnly: boolean;
}

export interface LandConfig {
  /** Board-up vs contacted wheel-support plane for a clean landing, deg (~25). */
  thetaCleanDeg: number;
  /** Extra clean cone by assist preset (Experienced, Classic, Streamlined). */
  cleanAssistBonusDeg: [number, number, number];
  /** Dirty landing limit, deg (~45); beyond is bail. */
  thetaDirtyDeg: number;
  /** Extra recoverable cone by assist preset. */
  dirtyAssistBonusDeg: [number, number, number];
  /** Travel speed below which heading alignment is irrelevant, m/s. */
  headingCheckMinSpeed: number;
  /** Board-forward vs travel alignment for a clean landing, modulo switch, deg. */
  headingCleanDeg: number;
  /** Largest recoverable sideways landing error, modulo switch, deg. */
  headingDirtyDeg: number;
  /** Largest surface-normal approach speed that can score clean, m/s. */
  impactSpeedCleanMax: number;
  /** Surface-normal approach speed beyond which the landing bails, m/s. */
  impactSpeedDirtyMax: number;
  /**
   * Fraction of horizontal speed scrubbed on a DIRTY landing (M4, hypothesis).
   * Applied by SimWorld as an opposing impulse (−mass·scrub·v_horizontal),
   * force/impulse-based — never a velocity write.
   */
  dirtySpeedScrub: number;
}

/**
 * Simcade transition/vert assistance. Rapier still owns contact and momentum;
 * these bounds only add rider-like pump/launch impulses and a near-aligned
 * landing correction at a detected sloped wheel support.
 */
export interface TransitionConfig {
  /** Minimum wheel-support slope that counts as transition geometry, degrees. */
  minSlopeDeg: number;
  /** Minimum horizontal uphill speed required to arm pump/lip assistance, m/s. */
  minApproachSpeed: number;
  /** Stable supported physics substeps required before a lip can arm. */
  minSupportedSubsteps: number;
  /** Consecutive unsupported substeps that confirm a real lip departure. */
  lipDepartureConfirmSubsteps: number;
  /** Maximum rider pump force along the current surface motion, N. */
  pumpForceMax: number;
  /** Transition speed at which automatic pump force fades fully out, m/s. */
  pumpSpeedLimit: number;
  /** Incoming uphill speed above the minimum converted to extra vertical speed. */
  lipLaunchSpeedGain: number;
  /** Hard cap on added lip-launch vertical speed, m/s. */
  lipLaunchDeltaSpeedMax: number;
  /** Forward share paired with the vertical launch so travel never reverses. */
  lipLaunchForwardShare: number;
  /** Hard cap on the complete lip-launch impulse, N·s. */
  lipLaunchImpulseMax: number;
  /** Airborne physics substeps required before transition landing help can open. */
  landingMinAirborneSubsteps: number;
  /** Board-up versus surface-normal cone in which landing help is allowed, deg. */
  landingAssistConeDeg: number;
  /** Surface alignment angular-speed correction gain, 1/s. */
  landingAlignRate: number;
  /** Fraction of surface-tangent angular velocity removed at contact. */
  landingAngularDamping: number;
  /** Hard cap on the landing correction torque impulse, N·m·s. */
  landingAngularImpulseMax: number;
}

/** Air-phase guards (M4). */
export interface AirConfig {
  /**
   * Max sim steps a maneuver may stay airborne before it bails with reason
   * 'timeout' (M4, hypothesis ~4 s — falling-out-of-world guard).
   */
  timeoutSteps: number;
}

/** Bail state tuning (M4). */
export interface BailConfig {
  /**
   * Steps the bail state lasts before the deterministic checkpoint respawn
   * (M4, hypothesis 1.5 s — long enough to read the failure).
   */
  recoverSteps: number;
  /**
   * Rigid-body linear+angular damping applied while bailed (M4, hypothesis).
   * Damping-parameter change integrated by the engine — not a velocity write.
   * Restored to the physics defaults on respawn.
   */
  dampingFactor: number;
}

export interface GrindConfig {
  /** Entry relative-speed window along rail, m/s. */
  vMin: number;
  vMax: number;
  /** Approach angle envelope half-width for 50-50 (near parallel), deg. */
  fiftyFiftyEnvelopeDeg: number;
  /** Boardslide requires |yaw vs rail| near 90° within this half-width, deg. */
  boardslideEnvelopeDeg: number;
  /** Snap radius by assist level, m (L0 ≈ 0). */
  rSnap: [number, number, number];
  /** Balance meter fail limit (|balance| > limit → slip). */
  balanceLimit: number;
  /** Balance drift gain from lateral lean / contact offset. */
  balanceGain: number;
  /** Hard off-axis impulse (N·s) that clears the latch. */
  interruptImpulse: number;

  // --- M6 grind detection / candidate signalling (hypothesis) ------------
  /**
   * Horizontal distance (m) from the board centre to the rail centre-line
   * within which a grind CANDIDATE is signalled (ObserveState.grind.candidate +
   * `grindCandidate` telemetry). MUST exceed `rSnap[2]` so the candidate always
   * appears BEFORE the latch — the visible-snap fairness mandate (research
   * §6.2/§9: "show icon when in snap volume so player trusts system"). Pure
   * feedback; never itself latches.
   */
  candidateVolumeRadius: number;
  /**
   * Steps after a pop during which a grind is still "recently popped" and thus a
   * candidate even if momentarily grounded (research §6.1: "candidate when
   * airborne OR recent pop"). Latch itself still only opens from the air phase.
   */
  recentPopSteps: number;
  /**
   * Board-centre ride height ABOVE the rail top surface, m, for each family. A
   * 50-50 straddles with the trucks on the rail (mirrors physics.truckDropY +
   * truckHalfExtents.y ≈ 0.085); a boardslide lies deck-flat (mirrors
   * deckThickness/2 ≈ 0.025). Used per-family for the tight vertical geometric-
   * contact test — NO loose vertical capture band (a generous band would be
   * vertical magnetism; the ~0.06 m family difference fits inside rSnap[1]).
   */
  rideHeightFiftyFifty: number;
  rideHeightBoardslide: number;

  // --- M6 soft-snap latch forces (hypothesis) ---------------------------
  /**
   * Lateral corrective spring gain per assist level, N per m of offset from the
   * rail centre-line (final-physics §4 latch: "lateral spring toward rail
   * centreline on entry"). L0 = 0 → pure physics, NO snap (a thin rail is then
   * genuinely hard); L1 default soft; L2 stronger. Never a pose write — applied
   * as a clamped horizontal force so the board is guided, not teleported.
   */
  latchLateralSpring: [number, number, number];
  /** Damping on the board's rail-perpendicular velocity, N per (m/s). Cancels sideways drift so the board tracks the rail. */
  latchLateralDamp: number;
  /** Hard clamp on the lateral corrective force magnitude, N (anti-explosion). */
  latchLateralForceMax: number;
  /**
   * Along-rail speed-proportional drag while grinding, 1/s. Bleeds grind speed so
   * a grind naturally ends (speed-end dismount) rather than riding forever —
   * force-based, never a velocity write.
   */
  tangentDrag: number;
  /** Along-rail speed (m/s) below which the grind speed-ends to a ground dismount. Below entry `vMin` for hysteresis (no instant exit at entry). */
  speedEndSpeed: number;

  // --- M6 balance meter (hypothesis; forgiving, no death loops) ----------
  /** Disturbance weight from the board's signed lateral offset from the centre-line. */
  balanceOffsetWeight: number;
  /** Disturbance weight from the board's signed roll relative to rail-up. */
  balanceRollWeight: number;
  /** Player counter-lean authority: balance correction per unit foot lateral bias. */
  balanceInputGain: number;
  /**
   * Self-centring decay of the balance meter, 1/s. Neutral play (no lean input)
   * eases balance back toward 0 so staying on is forgiving and a slip is always
   * recoverable — the anti-death-loop guarantee (research §5 "no inescapable
   * death loops").
   */
  balanceSelfCenter: number;
  /** Hard clamp on |balance| so the meter is always finite. */
  balanceClampMax: number;
  /** |balance| below this rides CLEAN (scores); between this and balanceLimit rides but dirty. */
  cleanBalanceBand: number;

  // --- M6 exits / interrupt (hypothesis) --------------------------------
  /** Vertical impulse (N·s) of an ollie-out hop off the rail, applied via the reused pop path. */
  exitHopImpulse: number;
  /**
   * Lateral impulse (N·s) kicking the board OFF the rail on a balance-fail slip,
   * plus `relatchCooldownSteps` of latch suppression, so a slip cannot instantly
   * re-latch within rSnap (the anti-oscillation guard — the specific death-loop
   * the mandate forbids).
   */
  slipLateralImpulse: number;
  /** Small upward impulse paired with an automatic dismount so hangers clear the rail instead of levering the deck inverted. */
  dismountLiftImpulse: number;
  /** Steps after ANY grind exit during which a new latch is suppressed (anti-oscillation). */
  relatchCooldownSteps: number;

  // --- M6 yaw alignment (hypothesis) — the orientation analog of the lateral
  // spring. A 50-50 is self-stabilising (momentum aligned with the board) but a
  // boardslide sits yawed ~90° across a thin line-contact that barely resists
  // yaw, so without this the board would pivot off. Aligns board heading to the
  // family target (parallel for 50-50, perpendicular for boardslide) with a
  // clamped torque — never a pose write. Near-zero for an already-aligned board.
  /** Yaw-align torque per rad of heading error, N·m/rad. */
  latchYawAlignGain: number;
  /** Yaw-rate damping while grinding, N·m per (rad/s). */
  latchYawDamp: number;
  /** Hard clamp on the yaw-align torque magnitude, N·m. */
  latchYawTorqueMax: number;
  /** Roll-level PD gains used while a default-assist grind is physically supported. */
  latchRollAlignGain: number;
  latchRollDamp: number;
  latchRollTorqueMax: number;
}

export interface PhysicsConfig {
  hz: number;
  gravity: { x: number; y: number; z: number };
  /** Board dimensions, m. */
  boardLength: number;
  boardWidth: number;
  wheelbase: number;
  /** Physical deck/trucks/wheels mass, kg. */
  boardMass: number;
  /** Invisible simcade rider/load proxy coupled to the playable board, kg. */
  riderMass: number;
  /** Fixed Rapier integration steps inside one 60 Hz gameplay step. */
  physicsSubsteps: number;
  /** Maximum nonlinear CCD substeps for the fast thin board/truck body. */
  ccdSubsteps: number;
  /** Ground locomotion. */
  pushImpulse: number;
  maxGroundSpeed: number;
  /**
   * Hard ceiling on commanded/servoed yaw rate, rad/s. Sized ABOVE any human
   * finger rotation (~12 rad/s ≈ 690°/s) so the clamp is an anti-cheat/NaN
   * boundary, never the thing that makes steering feel slow (reviews/03 §3.1).
   */
  steerYawRateMax: number;
  rollingFriction: number;
  /** Collision impulse above which maneuvers interrupt (T_col). */
  interruptCollisionImpulse: number;
  /** Smallest collision impulse reported to observability/landing logic. */
  contactReportImpulse: number;
  /**
   * Steps over which airborne contact impulses accumulate toward the
   * interrupt threshold (M4, hypothesis). The contact solver spreads a sharp
   * impact across ~2-3 steps at 60 Hz (measured: a 5.9 m/s wall crash reports
   * ~6 N·s on each of 3 consecutive steps, while a dirty-landing tail strike
   * is a single ~5.8 N·s step), so a windowed SUM separates "hard crash"
   * (~18 N·s > T_col) from "scrappy landing" (~6 N·s < T_col) where a
   * per-step magnitude cannot. The window resets whenever the board is
   * grounded and at each pop.
   */
  interruptWindowSteps: number;

  // --- Model A rigid body construction (M2) -----------------------------
  /**
   * Deck cuboid thickness, m (final-physics-animation-camera-spec §1: deck
   * cuboid ~0.05 thick). Long axis is local +Z, width is local X.
   */
  deckThickness: number;
  /** Half-extents of each truck box collider, m. */
  truckHalfExtents: { x: number; y: number; z: number };
  /**
   * |Z| offset of each truck box from board center, m. Two trucks at ±this
   * along the long axis (defaults to wheelbase / 2).
   */
  truckInsetZ: number;
  /**
   * Downward offset (m) of each truck box center below the deck center. With
   * truckDropY 0.055 and truck half-height 0.03 the truck undersides sit
   * 0.085 m below board center, so the resting board-center height is
   * ~0.085 m (observed ~0.084 with contact slop) — the spec's "deck height
   * ~0.09 m" class.
   */
  truckDropY: number;
  /** Physical ray-wheel radius, m. */
  wheelRadius: number;
  /** Lateral |X| offset of each wheel from the board centre, m. */
  wheelHalfTrack: number;
  /** Uncompressed suspension length below each wheel hard-point, m. */
  wheelSuspensionRestLength: number;
  /** Maximum suspension travel either side of rest length, m. */
  wheelMaxSuspensionTravel: number;
  /** Ray-wheel suspension spring stiffness. */
  wheelSuspensionStiffness: number;
  /** Suspension damping while compressing. */
  wheelSuspensionCompression: number;
  /** Suspension damping while relaxing. */
  wheelSuspensionRelaxation: number;
  /** Per-wheel suspension force clamp, N. */
  wheelMaxSuspensionForce: number;
  /** Longitudinal wheel grip used by the skateboard contact solver. */
  wheelFrictionSlip: number;
  /** Lateral tire grip multiplier; resists ice-like side slip. */
  wheelSideFrictionStiffness: number;
  /** Board center height at spawn/reset, m (board drops onto the ground). */
  spawnHeight: number;
  /**
   * Seeded reset position variation magnitude, m. Resets deliberately start
   * with zero angular velocity so the board never turns from an unseen shove.
   * Position still varies by seed for determinism/cross-seed coverage.
   */
  spawnJitter: number;
  /** Board (deck) collider friction coefficient. Deck grips rails/ledges. */
  boardFriction: number;
  /**
   * Truck collider friction coefficient (M3). The trucks are the ground-contact
   * geometry; keeping them low-friction models the wheels/trucks ROLLING so
   * gentle cruise forces are not pinned by static friction (μN ≈ 20 N at
   * boardMass). Deck keeps `boardFriction` for rail/ledge grip.
   */
  truckFriction: number;
  /**
   * Ground-proximity tolerance, m (M3). `isGrounded()` reports true when the
   * board center height is within this margin of its resting height
   * (truckDropY + truckHalfExtents.y). During the spawn drop the board is high,
   * so it reads NOT grounded until it settles — no ground forces mid-air.
   */
  groundedTolerance: number;
  /**
   * Minimum board-up alignment with world-up or the live wheel-support normal.
   * Height alone is insufficient: a deck resting on its edge is supported by
   * the floor, but it is not a stance a rider can stand on or steer from.
   */
  ridableDeckUpDot: number;
  /** Consecutive supported, unrideable steps before a deterministic recovery. */
  unrideableRecoverSteps: number;
  /** Board collider restitution (bounce). */
  boardRestitution: number;
  /** Board rigid-body linear/angular damping (settles the drop). */
  linearDamping: number;
  angularDamping: number;
  /** Static ground plane collider. Top surface sits at world y = 0. */
  ground: {
    halfExtents: { x: number; y: number; z: number };
    friction: number;
  };
}

/**
 * Ground-locomotion control gains (M3). These are CONTROLLER tunables (how
 * input maps to intent), distinct from the raw body/collider properties in
 * PhysicsConfig. BoardController emits body-state-free intents; SimWorld applies
 * them inside these clamps against live linear/angular velocity. All are
 * hypothesis defaults for G2 tuning.
 */
export interface LocomotionConfig {
  /**
   * Cruise asymptotic ground speed, m/s. Explicit Ctrl acceleration drives the
   * board toward this speed (below the hard `physics.maxGroundSpeed` cap).
   */
  cruiseTargetSpeed: number;
  /**
   * Nominal low-level cruise force, N (used by deterministic fixtures and
   * direct commands). SimWorld scales any authored drive force by
   * `(1 - forwardSpeed / cruiseTargetSpeed)` so drive fades to zero at the
   * target — force-based saturation, never a hard velocity write.
   */
  cruiseDriveForce: number;
  /** Peak force of one eased Ctrl push stroke, N. */
  accelerationStrokePeakForce: number;
  /** Active eased-force duration of each held-Ctrl push stroke, sim steps. */
  accelerationStrokeSteps: number;
  /** Start-to-start cadence of repeated held-Ctrl push strokes, sim steps. */
  accelerationCadenceSteps: number;
  /** Clamp for an explicit physical brake command, N. Shipping Ctrl release coasts. */
  coastBrakeForce: number;
  /** Minimum sim steps between push pulses (cooldown) so a held click is one push. */
  pushCooldownSteps: number;
  /**
   * Finger-line rotation → board yaw ratio (board rad per finger rad), applied
   * to the wrapPi segment-angle DELTA since dual-plant (reviews/03 design law:
   * relative ratchet steering, never the absolute pad angle). ~1.0–1.2 feels
   * 1:1; taste key, exposed for the tuning HUD.
   */
  steerDirectGain: number;
  /**
   * Heading-error → desired yaw-rate gain, 1/s (position loop of the direct
   * yaw servo). Sized so the board trails the fingers by a 30–50 ms time
   * constant; the feel-report steer gates (lagMs < 50, trackErrDeg < 5) are
   * the acceptance instrument for this value.
   */
  steerTrackGain: number;
  /**
   * Yaw servo gain, N·m per (rad/s) of yaw-rate error, executed as direct
   * clamped torque about deck-up (fingers planted = direct authority). Sized
   * against the loaded body's yaw inertia (~4.2 kg·m²) for a 1–2 step rate
   * response; torque limited by `steerMaxTorque` — no angular-velocity writes.
   */
  steerServoGain: number;
  /**
   * Steering torque clamp, N·m. Anti-cheat/NaN boundary, not realism: sized
   * so the servo OVERPOWERS the wheel-grip yaw moment at command rates
   * (fingers are an effectively infinite-stiffness constraint — grip never
   * gets a vote on heading, reviews/03 §2.1). Too low re-creates the audited
   * mush: the rate loop saturates against wheel side friction and the board
   * trails a fast rotation by >5°.
   */
  steerMaxTorque: number;
  /**
   * Grip model (heading ≠ travel): the slip angle between horizontal travel
   * and board-forward decays exponentially at this rate, 1/s (~125 ms time
   * constant) — momentum is ROTATED toward the deck, never deleted. Slow
   * rotation carves; fast rotation at speed out-runs the redirect and slides.
   */
  gripRate: number;
  /**
   * Redirect saturation: the grip can convert at most
   * gripRate × gripSlipSpeed (m/s of lateral velocity) per second, so at high
   * slip speeds the remainder keeps sliding (powerslide) instead of being
   * instantly re-aimed.
   */
  gripSlipSpeed: number;
  /** Actual deck lean → opposing front/rear truck steering gain. */
  truckLeanToSteer: number;
  /** Neutral rider lean below this angle is treated as truck/bearing noise. */
  truckLeanDeadzoneDeg: number;
  /** Physical truck steering clamp, degrees. */
  truckSteerMaxDeg: number;
  /** Speed-dependent truck steering attenuation per m/s. */
  truckSteerSpeedFade: number;
  /** Loaded-rider surface-alignment spring, N·m per radian of tilt error. */
  groundBalanceKp: number;
  /** Loaded-rider tilt-rate damping, N·m per rad/s. */
  groundBalanceKd: number;
  /** Maximum neutral rider balance torque while wheel-supported, N·m. */
  groundBalanceTorqueMax: number;
  /** Roll torque clamp, N·m (kept small so lean can never flip the board). */
  leanMaxRollTorque: number;
  /**
   * Scale mapping a calibrated pad offset-from-rest to a board-local shoe socket
   * offset (m) for ObserveState.feet. Presentation only; never drives physics.
   */
  padToBoardScale: number;
  /** Emit a sampled `groundControl` telemetry event every N sim steps (throttle). */
  groundControlLogEvery: number;
}

/**
 * App/runtime engine tunables introduced in M2. Not physics laws; these govern
 * the fixed-timestep loop, telemetry retention, and replay checkpoint cadence.
 */
export interface RuntimeConfig {
  loop: {
    /** Max real time (ms) folded into the accumulator per frame (anti-spiral). */
    maxFrameMs: number;
    /** Max fixed steps executed per rendered frame (anti-spiral clamp). */
    maxStepsPerFrame: number;
  };
  telemetry: {
    /** Bounded ring-log capacity (events beyond this drop oldest-first). */
    ringCapacity: number;
  };
  replay: {
    /** Emit a checkpoint hash every N sim steps while recording. */
    checkpointEverySteps: number;
  };
}

/**
 * Camera rig tunables (M7). PRESENTATION ONLY — the camera reads sim state via
 * the harness and never writes input/sim (spec §6: "camera never changes the
 * board-local input frame"). All values are cycle-3 hypothesis defaults for a
 * later feel pass; distances are metres, heights metres, FOV degrees. The rig
 * frames off `ObserveState.phase`; transitions are a critically damped spring on
 * position + a rate-clamped slerp on orientation (spec §6).
 */
export interface CameraConfig {
  /** Near/far clip planes, m. */
  near: number;
  far: number;
  /** Base (ground/chase) vertical FOV, deg. */
  fovBase: number;
  /** Air pull-back FOV, deg — widened so a full rotation reads (spec §6). */
  fovAir: number;

  // --- Chase low 3/4 (ground) -------------------------------------------
  /** Distance the chase cam sits BEHIND the board (along board heading −Z), m. */
  chaseDistance: number;
  /** Chase cam height above the board centre, m (feet stay visible). */
  chaseHeight: number;
  /** Lateral 3/4 offset of the chase cam, m (the "3/4" in low 3/4). */
  chaseSide: number;
  /** Faster riding pulls farther behind for route visibility. */
  chaseDistanceFast: number;
  /** Faster riding reduces the three-quarter offset without becoming dead-centre. */
  chaseSideFast: number;
  /** Speed where the fast chase offsets are fully applied, m/s. */
  chaseSpeedRef: number;
  /** Aim point height above the board centre for the look target, m. */
  aimHeight: number;
  /** Minimum look-ahead distance in front of the board, m. */
  lookAheadMin: number;
  /** Maximum look-ahead distance, m (reached at `lookAheadSpeedRef`). */
  lookAheadMax: number;
  /** Ground speed (m/s) at which look-ahead saturates to `lookAheadMax`. */
  lookAheadSpeedRef: number;

  // --- Optional close fingerboard view ---------------------------------
  /** Close-view distance behind the board, m. */
  fingerboardDistance: number;
  /** Close-view height above the deck, m. */
  fingerboardHeight: number;
  /** Close-view lateral offset, m; larger than distance for a tactile side view. */
  fingerboardSide: number;
  /** Close-view route look-ahead, m. */
  fingerboardLookAhead: number;

  // --- Air pull-back / catch --------------------------------------------
  /** Chase distance while airborne, m (pulled back for readability). */
  airDistance: number;
  /** Chase height while airborne, m. */
  airHeight: number;
  /**
   * Catch tightening factor in [0,1]: how far catch frames blend from the air
   * pose back toward the chase pose (0 = stay air, 1 = full chase).
   */
  catchTighten: number;

  // --- Bail wide --------------------------------------------------------
  /** Bail cam distance, m — wide so the failure is readable (spec §6). */
  bailDistance: number;
  /** Bail cam height, m. */
  bailHeight: number;
  /** Slow orbit rate while holding the bail wide shot, rad/s. */
  bailOrbitRate: number;

  // --- Grind overhead blend (STUB until M6 phase arrives) ----------------
  /** Grind cam height above the board, m (overhead-ish). */
  grindHeight: number;
  /** Grind cam lateral offset, m. */
  grindSide: number;
  /** Grind look-ahead along the rail, m. */
  grindLookAhead: number;

  // --- Transitions ------------------------------------------------------
  /**
   * Critically damped position smooth time, s (Unity-style SmoothDamp — the
   * analytic critically damped spring). Smaller = snappier. `reducedMotion`
   * snaps instantly regardless.
   */
  positionSmoothTime: number;
  /** Max camera angular slew rate, deg/s (orientation slerp clamp, spec §6). */
  maxAngularRateDeg: number;

  // --- Occlusion spring-arm ---------------------------------------------
  /** Sphere-cast probe radius for the occlusion spring-arm, m (spec §6). */
  occlusionRadius: number;
  /** Never shorten the arm below this distance from the target, m. */
  occlusionMinDistance: number;
}

/**
 * Presentation tunables (M7) for the shoes, wheels, and bail/respawn overlays.
 * PRESENTATION ONLY — none of these feed the sim. Blend RATES are per-second
 * exponential smoothing coefficients (`a = 1 − exp(−rate·dt)`), so they are
 * frame-rate independent and never pop. Cycle-3 hypothesis defaults.
 */
export interface PresentationConfig {
  /** Shoe follow rate on the ground (plant/rest tracking), 1/s. */
  shoeGroundBlendRate: number;
  /** Shoe rate while lerping back to sockets on catch, 1/s (spec §5 damp). */
  shoeCatchBlendRate: number;
  /** Air lean angle per unit board roll rate, rad per (rad/s) — cosmetic. */
  shoeAirLeanGain: number;
  /** Clamp on the procedural air lean, deg. */
  shoeAirLeanMaxDeg: number;
  /** Vertical squash of a planted shoe (1 = none), spec §5 "slight squash". */
  shoeSquashY: number;
  /** Render-space gravity for a bailed (detached) shoe, m/s². */
  bailShoeGravity: number;
  /** Tumble spin of a bailed shoe, rad/s (cosmetic). */
  bailShoeSpin: number;
  /** Bailed-shoe fade-out duration, ms. */
  bailShoeFadeMs: number;
  /**
   * Visual wheel-spin multiplier. Wheel angle accumulates
   * `+= (groundSpeed / wheelRadius) · dt · wheelSpinFactor` — never an absolute
   * angle derived from instantaneous speed (that stutters).
   */
  wheelSpinFactor: number;
  /** Fallback wheel radius, m, if the GLB wheel bbox can't be measured. */
  wheelRadiusFallback: number;
  /** Red bail vignette hold duration, ms (CSS overlay; skipped if reducedMotion). */
  bailVignetteMs: number;
  /** Respawn fade-through-black duration, ms (instant if reducedMotion). */
  respawnFadeMs: number;
}

export interface SimConfig {
  recognition: RecognitionConfig;
  footTracker: FootTrackerConfig;
  pop: PopConfig;
  flip: FlipConfig;
  catch: CatchConfig;
  land: LandConfig;
  transition: TransitionConfig;
  air: AirConfig;
  bail: BailConfig;
  grind: GrindConfig;
  physics: PhysicsConfig;
  locomotion: LocomotionConfig;
  runtime: RuntimeConfig;
  camera: CameraConfig;
  presentation: PresentationConfig;
}

// Deep-frozen at definition: the shared defaults are a contract, not a
// scratchpad. Tampering (including by injected agent code) throws in strict
// mode. Runs needing tweaked values must clone first (e.g. structuredClone).
export const DEFAULT_SIM_CONFIG: SimConfig = deepFreezeConfig({
  recognition: {
    cEnter: 0.55,
    cExit: 0.4,
    replaceMargin: 0.15,
    popLookbackMs: 60,
    popLookaheadMs: 60,
    stableClickContactMs: 32,
    airTrickWindowMs: 550,
    flickSpeedMin: 0.8,
    plantSpeedEps: 0.35,
    sweepMinAngleRad: 0.55,
    prepLiftSpeedMin: 0.8,
    shuvTargetDeg: 180,
    shuvNameMinDeg: 90,
  },
  footTracker: {
    recenterHoldMs: 300,
    ballisticPredictMs: 200,
    dualLiftClearMs: 500,
    idThrashWarnPerMin: 2,
    velEmaAlpha: 0.4,
    rebindRadius: 0.18,
    recenterRateHz: 1.5,
    motionTapMinLiftMs: 12,
    motionTapMaxLiftMs: 280,
    motionTapReplantRadius: 0.24,
  },
  pop: {
    actuationSubsteps: 4,
    jMin: 180,
    jMax: 300,
    baseQuality: 0.6,
    pitchBias: 0.35,
    // jY already includes the full board+rider load. This is a lever/feel
    // fraction, not another mass multiplier; scaling it with rider mass makes
    // a basic ollie somersault like a weightless toy.
    pitchTorqueScale: 0.04,
    pitchTorqueImpulseMax: 15.5,
    noseUpTargetDeg: 24,
    snapHoldSteps: 7,
    levelEndSteps: 30,
    // PD gains scale with the board+rider pitch inertia.
    levelKp: 186,
    levelKd: 25,
    levelTorqueMax: 46,
    prepLiftSpeedForMaxQ: 2.0,
    qTimingWeight: 0.5,
    qCrispWeight: 0.5,
    groundLeaveTimeoutSteps: 12,
  },
  flip: {
    omegaFlipMax: 15,
    kp: 8,
    kd: 0.6,
    tauMax: [37, 62, 93],
    impulseMax: [2.5, 4.3, 6.2],
    shuvImpulseMax: [12.4, 24.8, 37.2],
    guideDecaySteps: 20,
    axisDominanceRatio: 1.15,
    flickPathMinLen: 0.02,
    flickSpeedForMaxS: 5.0,
    shuvOmegaMax: 9.0,
    shuvTauMax: [155, 217, 310],
    quantizeConeDeg: [0, 45, 80],
    quantizeExtraDamp: [0, 0.5, 0.85],
    nameMinTurns: 0.4,
  },
  catch: {
    volumeRadius: 0.15,
    windowMs: 420,
    assistScale: [0.35, 0.55, 0.75],
    catchGain: 1.0,
    angularImpulseMax: [23, 46, 77],
    apexOnly: true,
  },
  land: {
    thetaCleanDeg: 25,
    cleanAssistBonusDeg: [0, 5, 10],
    thetaDirtyDeg: 70,
    dirtyAssistBonusDeg: [0, 0, 5],
    headingCheckMinSpeed: 0.75,
    headingCleanDeg: 30,
    headingDirtyDeg: 75,
    impactSpeedCleanMax: 5.5,
    impactSpeedDirtyMax: 10,
    dirtySpeedScrub: 0.35,
  },
  transition: {
    minSlopeDeg: 8,
    minApproachSpeed: 2,
    minSupportedSubsteps: 4,
    lipDepartureConfirmSubsteps: 2,
    // Local to a real uphill wheel contact and still below one Ctrl-stroke peak;
    // enough to carry a 74 kg loaded board through a one-metre return bank.
    pumpForceMax: 260,
    pumpSpeedLimit: 6.8,
    // The playable return lip is reached near 3.25 m/s; that earns ~2 m/s of
    // bounded lift. A simultaneous authored ollie stacks naturally for vert air.
    lipLaunchSpeedGain: 1.6,
    lipLaunchDeltaSpeedMax: 2.4,
    lipLaunchForwardShare: 0.18,
    lipLaunchImpulseMax: 190,
    landingMinAirborneSubsteps: 4,
    landingAssistConeDeg: 28,
    landingAlignRate: 5,
    landingAngularDamping: 0.35,
    landingAngularImpulseMax: 7,
  },
  air: {
    timeoutSteps: 240,
  },
  bail: {
    recoverSteps: 90,
    dampingFactor: 6.0,
  },
  grind: {
    vMin: 0.8,
    vMax: 9.0,
    fiftyFiftyEnvelopeDeg: 25,
    boardslideEnvelopeDeg: 40,
    // L1 is the default hardware experience: a centreline hit within roughly
    // half a deck-width should lock instead of producing an inert bounce.
    rSnap: [0.03, 0.24, 0.32],
    balanceLimit: 1.0,
    balanceGain: 1.6,
    interruptImpulse: 6,
    candidateVolumeRadius: 0.75,
    recentPopSteps: 36,
    rideHeightFiftyFifty: 0.085,
    rideHeightBoardslide: 0.025,
    latchLateralSpring: [0, 1705, 2790],
    latchLateralDamp: 434,
    latchLateralForceMax: 1860,
    tangentDrag: 0.9,
    speedEndSpeed: 0.5,
    balanceOffsetWeight: 3.2,
    balanceRollWeight: 0.7,
    balanceInputGain: 2.4,
    balanceSelfCenter: 2.2,
    balanceClampMax: 3.0,
    cleanBalanceBand: 0.45,
    exitHopImpulse: 228,
    slipLateralImpulse: 37.2,
    dismountLiftImpulse: 46.5,
    relatchCooldownSteps: 20,
    latchYawAlignGain: 186,
    latchYawDamp: 93,
    latchYawTorqueMax: 186,
    latchRollAlignGain: 62,
    latchRollDamp: 12.4,
    latchRollTorqueMax: 31,
  },
  physics: {
    hz: 60,
    gravity: { x: 0, y: -9.81, z: 0 },
    boardLength: 0.8,
    boardWidth: 0.2,
    wheelbase: 0.43,
    boardMass: 2.4,
    riderMass: 72,
    physicsSubsteps: 2,
    ccdSubsteps: 2,
    pushImpulse: 44,
    maxGroundSpeed: 6.5,
    steerYawRateMax: 12,
    rollingFriction: 0.18,
    interruptCollisionImpulse: 8,
    contactReportImpulse: 1,
    interruptWindowSteps: 3,
    deckThickness: 0.05,
    truckHalfExtents: { x: 0.05, y: 0.03, z: 0.03 },
    truckInsetZ: 0.215,
    truckDropY: 0.055,
    wheelRadius: 0.026,
    wheelHalfTrack: 0.086,
    wheelSuspensionRestLength: 0.034,
    wheelMaxSuspensionTravel: 0.025,
    wheelSuspensionStiffness: 240,
    wheelSuspensionCompression: 4.4,
    wheelSuspensionRelaxation: 5.2,
    wheelMaxSuspensionForce: 900,
    wheelFrictionSlip: 4,
    wheelSideFrictionStiffness: 30,
    spawnHeight: 0.6,
    spawnJitter: 0.02,
    boardFriction: 0.8,
    truckFriction: 0.06,
    groundedTolerance: 0.06,
    ridableDeckUpDot: 0.64,
    unrideableRecoverSteps: 45,
    boardRestitution: 0.1,
    linearDamping: 0.05,
    angularDamping: 0.2,
    ground: {
      // Keep the default free-skate floor beyond the camera horizon and beyond
      // a normal session's reachable distance. Physics and rendering consume
      // these same extents, so there is neither a visible nor a physical void
      // edge near the playable park.
      halfExtents: { x: 16_384, y: 0.1, z: 16_384 },
      friction: 0.9,
    },
  },
  locomotion: {
    cruiseTargetSpeed: 5.5,
    cruiseDriveForce: 220,
    accelerationStrokePeakForce: 710,
    accelerationStrokeSteps: 20,
    accelerationCadenceSteps: 34,
    coastBrakeForce: 0,
    pushCooldownSteps: 12,
    steerDirectGain: 1.1,
    steerTrackGain: 24,
    steerServoGain: 180,
    steerMaxTorque: 900,
    gripRate: 8,
    gripSlipSpeed: 1.2,
    truckLeanToSteer: 1.0,
    truckLeanDeadzoneDeg: 1.5,
    truckSteerMaxDeg: 18,
    truckSteerSpeedFade: 0.08,
    groundBalanceKp: 85,
    groundBalanceKd: 12,
    groundBalanceTorqueMax: 65,
    leanMaxRollTorque: 8.0,
    padToBoardScale: 0.6,
    groundControlLogEvery: 15,
  },
  runtime: {
    loop: { maxFrameMs: 250, maxStepsPerFrame: 5 },
    telemetry: { ringCapacity: 10000 },
    replay: { checkpointEverySteps: 30 },
  },
  camera: {
    near: 0.05,
    far: 400,
    fovBase: 46,
    fovAir: 52,
    chaseDistance: 1.2,
    chaseHeight: 0.72,
    chaseSide: -1.25,
    chaseDistanceFast: 2.4,
    chaseSideFast: -0.65,
    chaseSpeedRef: 6.0,
    aimHeight: 0.18,
    lookAheadMin: 0.35,
    lookAheadMax: 0.9,
    lookAheadSpeedRef: 6.0,
    fingerboardDistance: 0.12,
    fingerboardHeight: 0.62,
    fingerboardSide: -1.35,
    fingerboardLookAhead: 0.12,
    airDistance: 2.2,
    airHeight: 1.15,
    catchTighten: 0.55,
    bailDistance: 7.0,
    bailHeight: 3.0,
    bailOrbitRate: 0.25,
    grindHeight: 4.0,
    grindSide: 2.5,
    grindLookAhead: 2.5,
    positionSmoothTime: 0.32,
    maxAngularRateDeg: 150,
    occlusionRadius: 0.25,
    occlusionMinDistance: 0.8,
  },
  presentation: {
    shoeGroundBlendRate: 18,
    shoeCatchBlendRate: 9,
    shoeAirLeanGain: 0.06,
    shoeAirLeanMaxDeg: 18,
    shoeSquashY: 0.9,
    bailShoeGravity: -9.0,
    bailShoeSpin: 3.0,
    bailShoeFadeMs: 650,
    wheelSpinFactor: 1.0,
    wheelRadiusFallback: 0.026,
    bailVignetteMs: 900,
    respawnFadeMs: 250,
  },
} as SimConfig);

/** Fields the adaptive tuner may move, each within ±20% of default. */
export const AUTO_ADJUSTABLE_FIELDS = [
  "recognition.flickSpeedMin",
  "recognition.popLookbackMs",
  "recognition.popLookaheadMs",
  "catch.windowMs",
  "catch.volumeRadius",
] as const;

export function deepFreezeConfig<T>(cfg: T): T {
  if (cfg && typeof cfg === "object") {
    for (const value of Object.values(cfg as Record<string, unknown>)) {
      deepFreezeConfig(value);
    }
    Object.freeze(cfg);
  }
  return cfg;
}
